### ISSUE TITLE
どっかにはてなボタン用意して、押すと絵日記クラブのコンセプトが見れるようにする

### ISSUE THREAD

**Issue by cafe-lake** [cafe-lake/diary-crab#2]
### 表示する内容

　　　絵日記クラブが目指すもの
ここは平和な絵日記クラブ。みんな絵日記
を書いてシェアするクラブ。君はここでは
カニになる。描きたいままに書いて、他人
を気にせず自己満足な記録を残せばOK！
インスタグラムほど多くの機能はないし、
しっかりしてないと思います。けど、ゆっ
くりまったりやったっていいじゃない。
のんびりすこやかに🦀

**Comment by yuto33547** [comment]
![Uploading スクリーンショット 2024-03-06 0.26.45.png…]()

**Comment by yuto33547** [comment]
<img width="1440" alt="スクリーンショット 2024-03-06 0 31 49" src="https://github.com/cafe-lake/diary-crab/assets/149577049/ef3b5c47-32e7-4e33-931a-9adfd420ce08">
